[package]
name = "menu-rs"
version = "0.0.0"
description = "Cross-platform menu creation library."
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
once_cell = "1.10"

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
version = "0.34"
features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_Shell",
    "Win32_Globalization"
]

[target.'cfg(target_os = "linux")'.dependencies]
parking_lot = "0.12"
gtk = "0.15"

[dev-dependencies]
winit = "0.26"
tao = { path = "../tao", default-features = false }
